# Header
menu:
  首页: /
  归档: /archives
  关于: /about/index.html
rss: 
github: https://yxk17668.github.io/yxk17668/

# Content
excerpt_link: Read More
fancybox: true

# 数学公式
mathjax: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- tagcloud
- links

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: